apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapp
  namespace: myapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: weatherapp
  template:
    metadata:
      labels:
        app: weatherapp
    spec:
      containers:
        - name: weatherapp
          image: sharqm/weatherapp:latest
          ports:
            - containerPort: 5000
